{% set name = "amrex" %}
{% set version = "23.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AMReX-Codes/amrex/archive/refs/tags/{{ version }}.tar.gz
  sha256: e76e4787735c06ae747eaf57a682b12fed297ef2d5c7727051e20d34e4e79ce3
  patches:
    # Install CMake Scripts from Tools/CMake/ to <CMakePkgRoot>/Modules/
    # https://github.com/AMReX-Codes/amrex/pull/3599
    - 3599.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ccache        # [unix]
    - clang         # [win]
    - cmake
    - lld           # [win]
    # TODO: add libxml2 dep in lld-feedstock
    - libxml2       # [win]
    - make          # [unix]
    - ninja         # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
    - pkgconfig

test:
  commands:
    - test -f ${PREFIX}/lib/libamrex_1d.so  # [linux]
    - test -f ${PREFIX}/lib/libamrex_2d.so  # [linux]
    - test -f ${PREFIX}/lib/libamrex_3d.so  # [linux]
    - test -f ${PREFIX}/lib/libamrex_1d.dylib  # [osx]
    - test -f ${PREFIX}/lib/libamrex_2d.dylib  # [osx]
    - test -f ${PREFIX}/lib/libamrex_3d.dylib  # [osx]
    - if not exist %LIBRARY_PREFIX%\bin\amrex_1d.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\amrex_2d.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\amrex_3d.dll exit 1  # [win]

about:
  home: https://amrex-codes.github.io/amrex/
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: A software framework for massively parallel, block-structured adaptive mesh refinement (AMR) applications

  description: |
    AMReX is a software framework containing all the functionality to write
    massively parallel, block-structured adaptive mesh refinement (AMR)
    applications. AMReX is developed at LBNL, NREL, and ANL as part of the
    Block-Structured AMR Co-Design Center in DOE's Exascale Computing Project.

  doc_url: https://amrex-codes.github.io/amrex/docs_html/
  dev_url: https://github.com/AMReX-Codes/amrex

extra:
  recipe-maintainers:
    - atmyers
    - ax3l
    - WeiqunZhang
